// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import colors from 'src/tokens/colors';
import fontSizes from 'src/tokens/fontSizes';
import fontFamilies from 'src/tokens/fontFamilies';
import fontWeights from 'src/tokens/fontWeights';

const ProductDescriptionCss = `
color: ${colors['deepBlue']};
font-size: ${fontSizes['regular']};
font-family: ${fontFamilies['roboto']};
font-weight: ${fontWeights['standard']};
text-align: left;
`;

export default ProductDescriptionCss;