// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import spacing from 'src/tokens/spacing';
import borderWidths from 'src/tokens/borderWidths';
import radii from 'src/tokens/radii';
import colors from 'src/tokens/colors';
import fontSizes from 'src/tokens/fontSizes';
import fontFamilies from 'src/tokens/fontFamilies';
import fontWeights from 'src/tokens/fontWeights';
import lineHeights from 'src/tokens/lineHeights';
import letterSpacings from 'src/tokens/letterSpacings';

const ButtonCss = `
  width: 100%;
  box-sizing: border-box;
  border: 0;
  border-style: solid;
  height: ${spacing['big']};
  border-width: ${borderWidths['hairline']};
  border-color: rgba(45, 156, 219, 1);
  border-radius: ${radii['soft']};
  color: ${colors['white']};
  font-size: ${fontSizes['paragraph']};
  font-family: ${fontFamilies['light']};
  font-family: ${fontFamilies['regular']};
  font-family: ${fontFamilies['medium']};
  font-family: ${fontFamilies['bold']};
  font-weight: ${fontWeights['bold']};
  line-height: ${lineHeights['xs']};
  letter-spacing: ${letterSpacings['wide']};
  text-align: center;
  text-transform: uppercase;

  &.Normal {
    padding-left: ${spacing['small']};
    padding-right: ${spacing['small']};
    background-color: ${colors['blue1']};
    &:disabled {
      background-color: ${colors['gray1']};
    }
  }

  &.Warning {
    padding-left: ${spacing['small']};
    padding-right: ${spacing['small']};
    background-color: ${colors['orange']};
    &:disabled {
      background-color: ${colors['gray1']};
    }
    &:hover {
      background-color: ${colors['yellow']};
    }
  }

  &.Error {
    padding-left: ${spacing['small']};
    padding-right: ${spacing['small']};
    background-color: ${colors['red']};
    &:hover {
      background-color: rgba(123, 34, 34, 1);
    }
  }

`;

export default ButtonCss;