// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const mediaQueries = {
 "xs": "320px",
 "s": "580px",
 "m": "767px",
 "l": "1024px",
 "xl": "1440px"
}

module.exports = mediaQueries;