// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import spacing from 'src/tokens/spacing';
import colors from 'src/tokens/colors';
import borderWidths from 'src/tokens/borderWidths';
import radii from 'src/tokens/radii';
import shadows from 'src/tokens/shadows';
import fontSizes from 'src/tokens/fontSizes';
import fontFamilies from 'src/tokens/fontFamilies';
import fontWeights from 'src/tokens/fontWeights';
import lineHeights from 'src/tokens/lineHeights';

const InputCss = `
  width: 100%;
  box-sizing: border-box;
  border: 0;
  border-style: solid;
  padding-left: ${spacing['small']};
  padding-right: ${spacing['small']};
  height: ${spacing['big']};
  border-width: ${borderWidths['regular']};
  border-color: ${colors['black']};
  border-radius: ${radii['rounded']};
  box-shadow: ${shadows['soft']};
  font-size: ${fontSizes['paragraph']};
  font-family: ${fontFamilies['light']};
  font-family: ${fontFamilies['regular']};
  font-family: ${fontFamilies['medium']};
  font-family: ${fontFamilies['bold']};
  font-weight: ${fontWeights['regular']};
  line-height: ${lineHeights['xs']};
  text-align: left;

  &.Normal {
    background-color: ${colors['white']};
    color: ${colors['black']};
  }

  &:invalid {
    background-color: ${colors['black']};
    color: ${colors['red']};
  }

`;

export default InputCss;