// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import colors from 'src/tokens/colors';

const CardCss = `
  width: 100%;
  box-sizing: border-box;
  border: 0;
  border-style: solid;
  height: 488px;
  background-color: ${colors['white']};
`;

export default CardCss;